version: "1"
services:
  api:
    # REPLACE WITH DESIRED USERNAME
    image: <your username goes here>/boilerplate_back_end_web:tag
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.75"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - convene
networks:
  convene:
